## Configuration for the training, evaluation
samples:

  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_200MeV_*.h5

  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_250MeV_*.h5


  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_300MeV_*.h5

  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_350MeV_*.h5


  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_400MeV_*.h5

  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_450MeV_*.h5



  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_500MeV_*.h5

  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_550MeV_*.h5

  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_600MeV_*.h5

  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_650MeV_*.h5


  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_700MeV_*.h5

  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_750MeV_*.h5


  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_800MeV_*.h5

  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_850MeV_*.h5

  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_900MeV_*.h5

  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_950MeV_*.h5


  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/e_cla_new/h5_w2/e_1000MeV_*.h5
training:
    nDataLoaders : 4
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 300
    batch : 25
    learningRate : 0.0001
    randomSeed : 12346

    
