## Configuration for the training, evaluation
samples:
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_50MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_50MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_100MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_100MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_150MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_150MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_200MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_200MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_250MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_250MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_300MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_300MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_350MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_350MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_400MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_400MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_450MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_450MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_500MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_500MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_550MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_550MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_600MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_600MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_650MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_650MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_700MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_700MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_750MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_750MeV*.h5
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/KNO_cla_mu/h5/*_800MeV*.h5
  - name: e
    label : 1
    path: /store/cpnr/users/yewzzang/KNO_cla_e/h5/*_800MeV*.h5

training:
    nDataLoaders : 4
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 300
    batch : 30
    learningRate : 0.001
    randomSeed : 12346

    
