## Configuration for the training, evaluation
samples:
  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_200MeV_*.h5

  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_250MeV_*.h5


  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_300MeV_*.h5

  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_350MeV_*.h5


  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_400MeV_*.h5

  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_450MeV_*.h5



  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_500MeV_*.h5

  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_550MeV_*.h5


  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_600MeV_*.h5

  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_650MeV_*.h5



  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_700MeV_*.h5

  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_750MeV_*.h5


  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_800MeV_*.h5

  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_850MeV_*.h5

  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_900MeV_*.h5

  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_950MeV_*.h5


  - name: mu
    label : 0
    path: /store/cpnr/users/yewzzang/mu_cla_new/h5_w2/mu_1000MeV_*.h5

training:
    nDataLoaders : 4
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 300
    batch : 25
    learningRate : 0.0001
    randomSeed : 12346

    
