## Configuration for the training, evaluation
samples:

  - name: KNO
    path: /home/chyoo/work/KNO_VRDL/data/KNO_500_pmt500_dis3500/5m_*3.pt
  - name: KNO
    path: /home/chyoo/work/KNO_VRDL/data/KNO_500_pmt500_dis3500/5m_*5.pt
  - name: KNO
    path: /home/chyoo/work/KNO_VRDL/data/KNO_500_pmt500_dis3500/5m_*7.pt

training:
    nDataLoaders : 20
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 1000
    batch : 32
    learningRate : 0.01
    randomSeed : 123

    
model:
    fea : 5
    model: 'piver'
    cla : 3
    hidden : 256
    heads : 16
    posfeed : 256
    dropout : 0.1
    depths : 5
    pmts : 1000
    num_latents : 500
    query_dim : 256

    
    
