## Configuration for the training, evaluation
samples:
  # - name: KNO
    # path: /store/cpnr/users/yewzzang/KNO_mu_500/h5/mu_500MeV_1000.h5
  - name: KNO
    path: /store/cpnr/users/yewzzang/KNO_mu_500/h5/mu_500MeV_1*.h5
  - name: KNO
    path: /store/cpnr/users/yewzzang/KNO_mu_500/h5/mu_500MeV_2*.h5
  - name: KNO
    path: /store/cpnr/users/yewzzang/KNO_mu_500/h5/mu_500MeV_3*.h5
  - name: KNO
    path: /store/cpnr/users/yewzzang/KNO_mu_500/h5/mu_500MeV_4*.h5
  - name: KNO
    path: /store/cpnr/users/yewzzang/KNO_mu_500/h5/mu_500MeV_5*.h5
  - name: KNO
    path: /store/cpnr/users/yewzzang/KNO_mu_500/h5/mu_500MeV_6*.h5
  - name: KNO
    path: /store/cpnr/users/yewzzang/KNO_mu_500/h5/mu_500MeV_7*.h5


    
training:
    nDataLoaders : 8
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 1000
    batch : 80
    learningRate : 0.001
    randomSeed : 12346772345

    
model:
    fea : 5
    model: 'piver_mul_fullpmt'
    cla : 3
    hidden : 16
    heads : 4
    posfeed : 16
    dropout : 0.1
    depths : 9
    pmts : 1000
    num_latents : 200
    query_dim : 16

    
    
