## Configuration for the training, evaluation
samples:
  # - name: KNO
    # path: /home/chyoo/KNO_h5/ele_500MeV_cut/elec_KNO_Type3_20cov_500Mev_iso_evt_2k_fv0.5m_64.h5
  - name: KNO
    path: /home/chyoo/KNO_h5/ele_500MeV_cut/*1.h5
  - name: KNO
    path: /home/chyoo/KNO_h5/ele_500MeV_cut/*2.h5
  - name: KNO
    path: /home/chyoo/KNO_h5/ele_500MeV_cut/*3.h5
  - name: KNO
    path: /home/chyoo/KNO_h5/ele_500MeV_cut/*4.h5
  - name: KNO
    path: /home/chyoo/KNO_h5/ele_500MeV_cut/*5.h5
  - name: KNO
    path: /home/chyoo/KNO_h5/ele_500MeV_cut/*6.h5
    
training:
    nDataLoaders : 0
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 1000
    batch : 32
    learningRate : 0.001
    randomSeed : 12345

    
model:
    fea : 5
    model: 'piver_mul_fullpmt'
    cla : 3
    hidden : 16
    heads : 4
    posfeed : 16
    dropout : 0.1
    depths : 10
    pmts : 200
    num_latents : 200
    query_dim : 16

    
    
