## Configuration for the training, evaluation
samples:

  - name: KNO
    path: /home/chyoo/work/KNO_500_pmt500_dis3500/5m_*.pt


    
training:
    nDataLoaders : 20
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 500
    batch : 32
    learningRate : 0.001
    randomSeed : 12346772345

    
model:
    fea : 5
    model: 'piver'
    cla : 3
    hidden : 128
    heads : 16
    posfeed : 128
    dropout : 0.1
    depths : 5
    pmts : 1000
    num_latents : 200
    query_dim : 128

    
    
