## Configuration for the training, evaluation
samples:

  - name: KNO
    path: /home/chyoo/work/ele_500MeV_cut/*.h5


    
training:
    nDataLoaders : 10
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 1000
    batch : 32
    learningRate : 0.001
    randomSeed : 12346772345

    
model:
    fea : 5
    model: 'piver_mul_fullpmt'
    cla : 3
    hidden : 16
    heads : 4
    posfeed : 16
    dropout : 0.1
    depths : 9
    pmts : 1000
    num_latents : 200
    query_dim : 16

    
    
