## Configuration for the training, evaluation
samples:

  - name: KNO
<<<<<<< HEAD
    path: /store/cpnr/users/yewzzang/KNO_h5/ele_500MeV_cut/elec_KNO_Type3_20cov_500Mev_iso_evt_2k_fv0.5m_*6.h5
=======
    path: /home/chyoo/KNO_data/ele_500MeV_cut/elec_KNO_Type3_20cov_500Mev_iso_evt_2k_fv0.5m_*6.h5
    # path: /tmp/test_data/*.h5
  # - name: KNO
  #   path: /home/chyoo/KNO_data/ele_500MeV_cut/elec_KNO_Type3_20cov_500Mev_iso_evt_2k_fv0.5m_6.h5
  # - name: KNO
  #   path: /home/chyoo/KNO_data/ele_500MeV_cut/elec_KNO_Type3_20cov_500Mev_iso_evt_2k_fv0.5m_7.h5
  # - name: KNO
  #   path: /home/chyoo/KNO_data/ele_500MeV_cut/elec_KNO_Type3_20cov_500Mev_iso_evt_2k_fv0.5m_8.h5
  # - name: KNO
  #   path: /home/chyoo/KNO_data/ele_500MeV_cut/elec_KNO_Type3_20cov_500Mev_iso_evt_2k_fv0.5m_9.h5    
>>>>>>> 55a5dc0 (0321_hep2)


    
training:
    nDataLoaders : 4
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 10
    batch : 32
    learningRate : 0.001
    randomSeed : 12346772345

    
model:
    fea : 5
    model: 'piver_mul_fullpmt'
    cla : 3
    hidden : 16
    heads : 4
    posfeed : 16
    dropout : 0.1
    depths : 5
    pmts : 1000
    num_latents : 50
    query_dim : 16

    
    
