## Configuration for the training, evaluation
samples:

  # - name: KNO
  #   path: /home/chyoo/work/KNO_reconstruction/h5_file/KNO_500_pmt500_dis3500/5m_1.h5
  # - name: KNO
  #   path: /home/chyoo/work/KNO_reconstruction/h5_file/KNO_500_pmt500_dis3500/5m_2.h5
  # - name: KNO
  #   path: /home/chyoo/work/KNO_reconstruction/h5_file/KNO_500_pmt500_dis3500/5m_3.h5
  # - name: KNO
  #   path: /home/chyoo/work/KNO_reconstruction/h5_file/KNO_500_pmt500_dis3500/5m_4.h5
  # - name: KNO
  #   path: /home/chyoo/work/KNO_reconstruction/h5_file/KNO_500_pmt500_dis3500/5m_5.h5
  - name: KNO
    path: /home/chyoo/work/KNO_VRDL/data/KNO_500_pmt500_dis3500/*50.pt


    
training:
    nDataLoaders : 10
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 1000
    batch : 32
    learningRate : 0.001
    randomSeed : 12346772345

    
model:
    fea : 5
    model: 'piver'
    cla : 3
    hidden : 32
    heads : 4
    posfeed : 32
    dropout : 0.1
    depths : 5
    pmts : 1000
    num_latents : 500
    query_dim : 32

    
    
