## Configuration for the training, evaluation
samples:

  - name: elec
    label : 1
    path: /home/chyoo/work/KNO_elec_100_1000_pmt500_dis3500/*.pt
  
  - name: gamma
    label : 0
    path: /home/chyoo/work/KNO_gamma_100_1000_pmt500_dis3500/*.pt


    
training:
    nDataLoaders : 20
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 500
    batch : 32
    learningRate : 0.001
    randomSeed : 12346772345

    
model:
    fea : 5
    model: 'piver'
    cla : 1
    hidden : 128
    heads : 16
    posfeed : 128
    dropout : 0.1
    depths : 7
    pmts : 1000
    num_latents : 200
    query_dim : 128

    
    
