## Configuration for the training, evaluation
samples:

  - name: elec
    label : 1
    # path: /home/chyoo/KNO_data/elec_h5_cut/*.h5
    path: /tmp/test_data/elec_h5_cut/*.h5
    # path: /tmp/test_data/elec_h5_cut/elec_KNO_Type3_20cov_400Mev_iso_evt_2k_fv0.5m_9.h5
    # path: /home/chyoo/KNO_data/elec_h5_cut/elec_KNO_Type3_20cov_400Mev_iso_evt_2k_fv0.5m_9.h5
  
  - name: mu
    label : 0
    # path: /home/chyoo/KNO_data/mu_h5_cut/*.h5
    path: /tmp/test_data/mu_h5_cut/*.h5
    # path: /tmp/test_data/mu_h5_cut/mu_KNO_Type3_20cov_400Mev_iso_evt_2k_fv0.5m_9.h5
    # path: /home/chyoo/KNO_data/mu_h5_cut/mu_KNO_Type3_20cov_400Mev_iso_evt_2k_fv0.5m_9.h5


    
training:
    nDataLoaders : 8
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 1000
    batch : 20
    learningRate : 0.001
    randomSeed : 12346772345

    
model:
    fea : 5
    model: 'piver_mul_fullpmt'
    cla : 1
    hidden : 16
    heads : 4
    posfeed : 16
    dropout : 0.1
    depths : 5
    pmts : 1000
    num_latents : 500
    query_dim : 16

    
    
